services:
  server:
    build:
      context: ./server
    container_name: ecommerce-server
    env_file:
      - ./server/.env
    ports:
      - "1111:1111"
    restart: unless-stopped

  client:
    build:
      context: ./client
      args:
        VITE_API_URL: http://100.58.109.23:1111
        VITE_STRIPE_PUBLIC_KEY: $VITE_STRIPE_PUBLIC_KEY
    container_name: ecommerce-client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped
